### ISSUE TITLE
Namespace exclusion?

### ISSUE THREAD

**Issue by cjohnsonuk** [dwp-forge/batchedit#49]
Is it possible to exclude multiple namespaces from the search so that for example audit records referring to the search term are not replaced?  I have 100 instances of the search term across the whole wiki but only two namespaces I don't want to include in the replacement, :meetings and :audit

**Comment by dwp-forge** [comment]
Currently such feature is not supported.

The easiest way to do this coming to my mind would be to temporarily move the namespaces you want to skip out of /pages, apply the replacement to the remaining pages and then move those namespaces back. That is, if you have access to the DW file system, which I guess you do, since you are using admin plugins.

**Comment by dwp-forge** [comment]
Implemented in [v.2023-06-16](https://github.com/dwp-forge/batchedit/releases/tag/v.2023-06-16).
