### ISSUE TITLE
Older DW Versions now broken

### ISSUE THREAD

**Issue by gamma** [dwp-forge/batchedit#51]
After upgrading to the latest version, I can not use the plugin in an older installation anymore:

    [Mon Aug 14 07:38:43.148748 2023] [php7:error] [pid 2916156] [client 10.10.0.2:57772] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\File\\Resolver' not found in .../lib/plugins/batchedit/request.php:17\nStack trace:\n#0 .../lib/plugins/batchedit/admin.php(13): require_once()\n#1 .../lib/plugins/batchedit/action.php(10): require_once('/var/www/www.in...')\n#2 .../inc/load.php(147): require('/var/www/www.in...')\n#3 [internal function]: load_autoload()\n#4 [internal function]: spl_autoload_call()\n#5 .../inc/Extension/PluginController.php(103): class_exists()\n#6 .../inc/pluginutils.php(54): dokuwiki\\Extension\\PluginController->load()\n#7 .../inc/Extension/EventHandler.php(32): plugin_load()\n#8 .../inc/init.php(221): dokuwiki\\Extension\\EventHandler->__construct()\n#9 .../doku.php(36): require_ in .../lib/plugins/batchedit/request.php on line 17, referer: https://...?do=admin&page=extension&tab=plugins

**Comment by dwp-forge** [comment]
If you choose to use an older version of DW, I would recommend to use an older version of the plugin as well.

Old releases are available [here](https://github.com/dwp-forge/batchedit/tags).

**Comment by gamma** [comment]
Thanks, that's what I did. It's a bit sad though, that the wiki completely breaks when updating using the manager. Not sure if the plugin already defines that it is incompatible with older versions and how the manager displays that fact. Except the message that the download url changed, there is no further hint.

**Comment by dwp-forge** [comment]
AFAIK, there is not much of version compatibility framework beyond listing supported DW versions on the plugin page. The extension manager mostly relies on [plugin.info.txt file](https://www.dokuwiki.org/devel:plugin_info), which has no compatibility information. So the only way to maintain backward compatibility is to keep multiple implementations of a particular feature in the plugin code and switch between them based on DW version. There could be some potential benefit in developing such feature, but since DW tries to promote the latest stable version, I guess, the audience for it would be rather limited.
